### ISSUE TITLE
[TOPAZ] Clock shortcut on lockscreen causes a crash.

### ISSUE THREAD

**Issue by rk134** [AOSPA/Tracker#5]
**Describe the bug**
If a alarm is set, locking the device, and clicking on the clock smartspace shortcut causes a SystemUI crash, and forces it to reload.

**To Reproduce**
1. Go to the clock app.
2. Set an alarm in 5-10 minutes time (any time can be set)
3. Lock device.
4. Wake device, and click on alarm icon in smartspace.
5. Watch your device crash 😆 

**Expected behavior**
If the device is locked, it should prompt for unlock, and directly take you to the clock app.
If the device is unlocked, it should prompt you to swipe up, and it should directly take you to the clock app.

**Actual behavior**
SystemUI crashes.

**Additional context**
Not device specific, seems to be in topaz builds only.

**Comment by timocapa** [comment]
log:

```
05-17 01:19:06.425 20622 20622 D AndroidRuntime: Shutting down VM
05-17 01:19:06.426 20622 20622 E AndroidRuntime: FATAL EXCEPTION: main
05-17 01:19:06.426 20622 20622 E AndroidRuntime: Process: com.android.systemui, PID: 20622
05-17 01:19:06.426 20622 20622 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.smartspace.SmartspaceTarget.getFeatureType()' on a null object reference
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at com.google.android.systemui.smartspace.BcSmartSpaceUtil.-$$Nest$smhijackIntent(BcSmartSpaceUtil.java:6)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at com.google.android.systemui.smartspace.BcSmartSpaceUtil$1.onClick(BcSmartSpaceUtil.java:36)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.view.View.performClick(View.java:7506)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7483)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:29361)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7939)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-17 01:19:06.426 20622 20622 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
